/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import securechar_server.DbServices;

/**
 *
 * @author Kareem Lawal
 */
public class MainForm extends javax.swing.JFrame {

    private DbServices services;

    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        socketList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        onlineList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sessionList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        AuthenticationBtn = new javax.swing.JButton();
        TerminateServerBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        fileSocketList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVER");
        setMinimumSize(new java.awt.Dimension(690, 500));
        setSize(new java.awt.Dimension(927, 480));
        getContentPane().setLayout(null);

        socketList.setBackground(new java.awt.Color(242, 242, 242));
        socketList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(socketList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 230, 170);

        onlineList.setBackground(new java.awt.Color(242, 242, 242));
        onlineList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(onlineList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 35, 145, 340);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Sockets");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 180, 150, 30);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Online Users");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 10, 119, 30);

        logText.setBackground(new java.awt.Color(242, 242, 242));
        logText.setColumns(20);
        logText.setRows(5);
        jScrollPane3.setViewportView(logText);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 34, 230, 130);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Log");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 220, 20);

        sessionList.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane4.setViewportView(sessionList);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(270, 35, 220, 130);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Session Log");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 10, 150, 30);

        AuthenticationBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        AuthenticationBtn.setText("Authentication Management");
        AuthenticationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthenticationBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AuthenticationBtn);
        AuthenticationBtn.setBounds(10, 400, 230, 42);

        TerminateServerBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TerminateServerBtn.setText("Terminate Server");
        TerminateServerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminateServerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(TerminateServerBtn);
        TerminateServerBtn.setBounds(270, 400, 220, 44);

        fileSocketList.setBackground(new java.awt.Color(242, 242, 242));
        fileSocketList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(fileSocketList);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(270, 210, 220, 170);

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("File Sockets ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 190, 160, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuthenticationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthenticationBtnActionPerformed
        AuthenticationManagementForm auth = new AuthenticationManagementForm();
        auth.setVisible(true);
    }//GEN-LAST:event_AuthenticationBtnActionPerformed

    private void TerminateServerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminateServerBtnActionPerformed

        System.exit(0);
    }//GEN-LAST:event_TerminateServerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AuthenticationBtn;
    private javax.swing.JButton TerminateServerBtn;
    public static javax.swing.JList fileSocketList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTextArea logText;
    public static javax.swing.JList onlineList;
    public static javax.swing.JList sessionList;
    public static javax.swing.JList socketList;
    // End of variables declaration//GEN-END:variables
}
